version: "3.7"

services:

#----------------------------------------------------------------------------------
    pgadmin:
        container_name: pgadmin_new
        image: dpage/pgadmin4
        networks:
            my_network:
                ipv4_address: 172.20.0.40
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
            - PGADMIN_LISTEN_ADDRESS=0.0.0.0
            - PGADMIN_LISTEN_PORT=5123

#----------------------------------------------------------------------------------
    flower_redis_first:
        container_name: flower_new_first
        image: mher/flower:0.9.7
        command: ['flower', '--url_prefix=flower_first']
        networks:
            my_network:
                ipv4_address: 172.20.0.41
        environment:
            - CELERY_BROKER_URL=redis://redis_new:6379/0
            - FLOWER_PORT=5801

#----------------------------------------------------------------------------------
#    flower_redis_two:
#        container_name: flower_new_two
#        image: mher/flower:0.9.7
#        command: ['flower', '--url_prefix=flower_two']
#        networks:
#            my_network:
#                ipv4_address: 172.20.0.42
#        environment:
#            - CELERY_BROKER_URL=redis://redis_new:6379/2
#            - FLOWER_PORT=5802

#----------------------------------------------------------------------------------
networks:
    my_network:
        name: app_net_new
        external: true
