[project]
name = "fast-api-two-2-reformat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"

requires-python = ">=3.12"

dependencies = [
    "aiohttp==3.13.2",
    "alembic>=1.17.2",
    "async-timeout>=5.0.1",
    "asyncpg>=0.31.0",
    "bcrypt>=5.0.0",
    "black>=25.12.0",
    "celery==5.6.0",
    "celery-types>=0.24.0",
    "fastapi==0.127.0",
    "flower>=2.0.1",
    "multipledispatch==1.0.0",
    "psycopg2-binary>=2.9.11",
    "pydantic==2.12.5",
    "python-dotenv==1.2.1",
    "python-editor>=1.0.4",
    "python-multipart>=0.0.21",
    "redis>=7.1.0",
    "sqlalchemy==2.0.45",
    "starlette==0.50.0",
    "typing-extensions==4.15.0",
    "uvicorn==0.40.0",
    "aiosqlite>=0.22.1",
]



[tool.ruff.lint]
ignore = [
    "F401",
    "E402",
    "F541"
]

[tool.ruff]
line-length = 120
indent-width = 4
exclude = [
    ".git",
    "log",
    ".mypy_cache",
    ".ruff_cache",
    ".venv",
    "venv",
    ".vscode",
    "__pypackages__",
    "__pycache__",
    "_build",
    "build",
    "dist",
    "node_modules",
    "site-packages"
]



[tool.black]
line-length = 120
exclude = '''
/(
  # directories
  \.venv
  | venv
  | \.git
  | \.log
  | \.mypy_cache
  | \.tox
  | build
  | dist
)/
'''
