"""empty message

Revision ID: 081987267877
Revises:
Create Date: 2024-03-16 15:10:52.815274

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "081987267877"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
