"""empty message

Revision ID: 0ac572f4f68c
Revises: 9baa2b2b5888
Create Date: 2024-04-14 08:23:29.127972

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0ac572f4f68c"
down_revision = "9baa2b2b5888"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "joinaddress",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("city", sa.String(length=20), nullable=True),
        sa.Column("street", sa.String(length=20), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_joinaddress_id"), "joinaddress", ["id"], unique=False)
    op.create_table(
        "joinperson",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("name", sa.String(length=20), nullable=True),
        sa.Column("surname", sa.String(length=20), nullable=True),
        sa.Column("addr_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_joinperson_id"), "joinperson", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_joinperson_id"), table_name="joinperson")
    op.drop_table("joinperson")
    op.drop_index(op.f("ix_joinaddress_id"), table_name="joinaddress")
    op.drop_table("joinaddress")
    # ### end Alembic commands ###
