"""admin list work

Revision ID: 7c366604c24a
Revises: 0a2bfa0f93ca
Create Date: 2026-01-11 19:36:40.292495

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7c366604c24a"
down_revision = "0a2bfa0f93ca"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_list",
        sa.Column("admin_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("admin_id"),
        sa.UniqueConstraint("admin_id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "admin_work",
        sa.Column("admin_work_id", sa.BIGINT(), nullable=False),
        sa.Column("type_work", sa.String(), nullable=False),
        sa.Column("callback_data", sa.String(), nullable=False),
        sa.Column("admin_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["admin_id"], ["admin_list.admin_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("admin_work_id"),
        sa.UniqueConstraint("admin_work_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("admin_work")
    op.drop_table("admin_list")
    # ### end Alembic commands ###
