"""joinperson joinaddress

Revision ID: 0a2bfa0f93ca
Revises: 9611a1cadbfa
Create Date: 2026-01-11 19:35:11.520681

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0a2bfa0f93ca"
down_revision = "9611a1cadbfa"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "joinaddress",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("city", sa.String(length=20), nullable=True),
        sa.Column("street", sa.String(length=20), nullable=True),
        sa.Column("addr_index", sa.Integer(), nullable=True),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_joinaddress_id"), "joinaddress", ["id"], unique=False)
    op.create_table(
        "joinperson",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=True),
        sa.Column("surname", sa.String(length=20), nullable=True),
        sa.Column("link_addr", sa.Integer(), nullable=True),
        sa.Column(
            "time_created",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_joinperson_id"), "joinperson", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_joinperson_id"), table_name="joinperson")
    op.drop_table("joinperson")
    op.drop_index(op.f("ix_joinaddress_id"), table_name="joinaddress")
    op.drop_table("joinaddress")
    # ### end Alembic commands ###
