"""empty message

Revision ID: 2755aece8051
Revises: 6cd9bb1cd965
Create Date: 2024-04-14 20:40:02.208963

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2755aece8051"
down_revision = "6cd9bb1cd965"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "admin_list", ["admin_id"])
    op.create_unique_constraint(None, "admin_work", ["admin_work_id"])
    op.drop_constraint("admin_work_admin_id_fkey", "admin_work", type_="foreignkey")
    op.create_foreign_key(
        None,
        "admin_work",
        "admin_list",
        ["admin_id"],
        ["admin_id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("posts_user_id_fkey", "posts", type_="foreignkey")
    op.create_foreign_key(None, "posts", "users", ["user_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "posts", type_="foreignkey")
    op.create_foreign_key("posts_user_id_fkey", "posts", "users", ["user_id"], ["id"])
    op.drop_constraint(None, "admin_work", type_="foreignkey")
    op.create_foreign_key(
        "admin_work_admin_id_fkey",
        "admin_work",
        "admin_list",
        ["admin_id"],
        ["admin_id"],
    )
    op.drop_constraint(None, "admin_work", type_="unique")
    op.drop_constraint(None, "admin_list", type_="unique")
    # ### end Alembic commands ###
