"""empty message

Revision ID: 58e2560fa36c
Revises: 869b45bd63f9
Create Date: 2024-04-20 09:56:01.483895

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "58e2560fa36c"
down_revision = "869b45bd63f9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("idx_unique_reader_list", "listbooks", ["reader_id", "list_name"])
    op.create_unique_constraint(None, "readers", ["nickname"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "readers", type_="unique")
    op.drop_constraint("idx_unique_reader_list", "listbooks", type_="unique")
    # ### end Alembic commands ###
