"""empty message

Revision ID: 889d453f9989
Revises: 0ac572f4f68c
Create Date: 2024-04-14 09:23:05.575870

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "889d453f9989"
down_revision = "0ac572f4f68c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("joinaddress", sa.Column("addr_index", sa.Integer(), nullable=True))
    op.add_column("joinperson", sa.Column("link_addr", sa.Integer(), nullable=True))
    op.drop_column("joinperson", "addr_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "joinperson",
        sa.Column("addr_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_column("joinperson", "link_addr")
    op.drop_column("joinaddress", "addr_index")
    # ### end Alembic commands ###
