"""empty message

Revision ID: a83e4b4426ce
Revises: c4863d257286
Create Date: 2024-04-11 19:05:28.650137

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a83e4b4426ce"
down_revision = "c4863d257286"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "order_product_association_order_id_fkey",
        "order_product_association",
        type_="foreignkey",
    )
    op.drop_constraint(
        "order_product_association_product_id_fkey",
        "order_product_association",
        type_="foreignkey",
    )
    op.create_foreign_key(None, "order_product_association", "orders", ["order_id"], ["id"])
    op.create_foreign_key(None, "order_product_association", "products", ["product_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "order_product_association", type_="foreignkey")
    op.drop_constraint(None, "order_product_association", type_="foreignkey")
    op.create_foreign_key(
        "order_product_association_product_id_fkey",
        "order_product_association",
        "products",
        ["product_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "order_product_association_order_id_fkey",
        "order_product_association",
        "orders",
        ["order_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
